name: testing branch

on: 
  push:
    branches:
      - dev
 
jobs:
  new_branch: 

    runs-on: ubuntu-latest
    steps: 
      - name: ENV CMDS
        run: |
          node -v
          mvn -v
          java -version

