name: this is the first git-hub actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: echo cmd testing
        run: echo " it is working"
  
  job2:
    runs-on: ubuntu-latest
    needs: [job1]

    steps:
      - name: building
        run: |
          x=2
          y=2
          r=x+y
          print(f" {x} + {y} = {r} ")
        shell: python          
                 
        
