name: this is the first git-hub actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: echo cmd testing
        run: echo " it is working"
  
  job2:
    #job2 will run on a different instance, as we have
    # separated, similar to master slave in jenkins.
    runs-on: ubuntu-latest
    needs: [job1]
    # "Needs" is used to make sure the first job 
    # is completed and then run the next job.

    steps:
      - name: building
        run: |
          x=2
          y=2
          l=339
          r=x+y
          print(f" {x} + {y} = {r} ")
        shell: python 
        
        #  to run it with any partiuclar shell,
        #  in this example we r running it with python 
        # instead of default shell in this particular
        #  step.
          
        
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Testing "with" & Outputs From actions
        id: greet #ID for referencing in next steps.
        uses: actions/hello-world-javascript-action@v1

        with: 
          who-to-greet: Testing Actions
      - name: Outputting info from actions file key.
        run: |
          echo "${{steps.name.outputs.time}}"
          pwd
          ls
